version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: django_rest_template
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver"
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
    restart: always     # or "unless-stopped"
