version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: django_rest_template
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always # or "unless-stopped"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db
    restart: always # or "unless-stopped"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
      - pgadmin
    restart: always # or "unless-stopped"

